sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t motpansergiu/react-test-eb -f ./client/Dockerfile.dev ./client

script: 
 - docker run -e CI=true motpansergiu/react-test-eb npm test

after_success: 
  - docker build -t motpansergiu/multi-client-eb ./client
  - docker build -t motpansergiu/multi-nginx-eb ./nginx
  - docker build -t motpansergiu/multi-server-eb ./server
  - docker build -t motpansergiu/multi-worker-eb ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push motpansergiu/multi-client-eb
  - docker push motpansergiu/multi-nginx-eb
  - docker push motpansergiu/multi-server-eb
  - docker push motpansergiu/multi-worker-eb

deploy:
 provider: elasticbeanstalk
 region: "eu-central-1"
 app: "multi-docker"
 env: "Multi-docker-env"
 bucket_name: "elasticbeanstalk-eu-central-1-578452386702"
 bucket_path: "multi-docker"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"