sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t motpansergiu/react-test -f ./client/Dockerfile.dev ./client

script: 
 - docker run -e CI=true motpansergiu/react-test npm test

after_success: 
  - docker build -t motpansergiu/multi-client ./client
  - docker build -t motpansergiu/multi-nginx ./nginx
  - docker build -t motpansergiu/multi-server ./server
  - docker build -t motpansergiu/multi-worker ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push motpansergiu/multi-client
  - docker push motpansergiu/multi-nginx
  - docker push motpansergiu/multi-server
  - docker push motpansergiu/multi-worker
